window.portfolioProjects = [
  {
    slug: "unicef",
    title: "Unicef",
    category: "SMM Design",
    image: "images/p1.jpg",
    year: "2026",
    role: "SMM designer",
    intro: "Социальная digital-серия с чистой и доверительной подачей.",
    brief: "Собрать визуальный язык для публикаций, которые быстро читаются в ленте и сохраняют серьезный тон темы.",
    idea: "Мягкая типографика, ясная сетка и акценты, которые помогают сообщению быть первым, что видит зритель.",
    result: "Подготовлены карточки, обложки и формат для регулярной коммуникации бренда.",
    tags: ["social", "layout", "awareness"]
  },
  {
    slug: "samruk-kazyna-store",
    title: "Samruk Kazyna Store",
    category: "Графический дизайн",
    image: "images/p2.jpg",
    year: "2026",
    role: "graphic designer",
    intro: "Коммерческая графика для каталога и промо-материалов.",
    brief: "Сделать подачу продуктов аккуратной, понятной и достаточно яркой для онлайн-витрины.",
    idea: "Использовать крупные товарные зоны, короткие подписи и спокойные цветовые блоки.",
    result: "Собран набор визуалов для промо, карточек и внутренних презентаций.",
    tags: ["store", "promo", "visual system"]
  },
  {
    slug: "kazakhtelecom",
    title: "Kazakhtelecom",
    category: "SMM Design",
    image: "images/p3.jpg",
    year: "2026",
    role: "SMM designer",
    intro: "Динамичная серия для технологичного бренда и его сервисов.",
    brief: "Объяснить услуги через простые визуальные сценарии, без перегруза техническими деталями.",
    idea: "Соединить строгую сетку, контрастные заголовки и иллюстративные элементы интерфейса.",
    result: "Получился набор материалов, который можно масштабировать под разные форматы соцсетей.",
    tags: ["tech", "SMM", "service"]
  },
  {
    slug: "alt-university",
    title: "ALT University",
    category: "Брендинг",
    image: "images/p4.jpg",
    year: "2026",
    role: "brand designer",
    intro: "Образовательная айдентика с энергией кампуса и ясной навигацией.",
    brief: "Собрать стиль, который одинаково уверенно работает в афишах, постах и презентациях.",
    idea: "Опора на сильные заголовки, модульную сетку и знаки движения.",
    result: "Подготовлен визуальный набор для студенческих и имиджевых коммуникаций.",
    tags: ["branding", "education", "campus"]
  },
  {
    slug: "asia-park",
    title: "Asia Park",
    category: "SMM Design",
    image: "images/p5.jpg",
    year: "2026",
    role: "SMM designer",
    intro: "Контент для торгового центра с акцентом на события и настроение.",
    brief: "Сделать публикации заметными, но сохранить удобство чтения акций и анонсов.",
    idea: "Яркие промо-плашки, крупная фотография и быстрые информационные блоки.",
    result: "Система постов для событий, скидок и сезонных кампаний.",
    tags: ["mall", "events", "promo"]
  },
  {
    slug: "riviera-international-school",
    title: "Riviera International School",
    category: "Брендинг",
    image: "images/p6.jpg",
    year: "2026",
    role: "brand designer",
    intro: "Спокойный и уверенный визуальный стиль для международной школы.",
    brief: "Передать доверие, академичность и живую атмосферу обучения.",
    idea: "Чистые поля, мягкие акценты и фотографичная композиция вокруг людей.",
    result: "Собраны носители для презентаций, соцсетей и информационных материалов.",
    tags: ["school", "identity", "editorial"]
  },
  {
    slug: "high-school-of-burabay",
    title: "High School of Burabay",
    category: "Графический дизайн",
    image: "images/p7.jpg",
    year: "2026",
    role: "graphic designer",
    intro: "Визуальная упаковка для школьного проекта с чистой структурой.",
    brief: "Сделать материалы современными и удобными для учеников, родителей и команды школы.",
    idea: "Простая сетка, контрастные карточки и дружелюбный образовательный тон.",
    result: "Подготовлены макеты для печатных и digital-носителей.",
    tags: ["school", "print", "digital"]
  },
  {
    slug: "plus-one-fund",
    title: "Благотворительный фонд +1",
    category: "SMM Design",
    image: "images/p8.jpg",
    year: "2026",
    role: "SMM designer",
    intro: "Эмоциональная SMM-серия для благотворительного фонда.",
    brief: "Сделать коммуникацию теплой и понятной, без визуального давления на зрителя.",
    idea: "Мягкие цвета, ясные призывы и фотографии как главный носитель смысла.",
    result: "Собран набор постов для сборов, отчетов и историй фонда.",
    tags: ["charity", "social", "stories"]
  },
  {
    slug: "astana-hub-ventures",
    title: "Astana Hub Ventures",
    category: "Брендинг",
    image: "images/p9.jpg",
    year: "2026",
    role: "brand designer",
    intro: "Стартап-визуал с ощущением скорости, питча и роста.",
    brief: "Создать подачу для венчурной среды, где важны цифры, команда и уверенность.",
    idea: "Контрастная типографика, крупные маркеры и структура pitch deck.",
    result: "Визуальная система для презентаций, постов и анонсов.",
    tags: ["startup", "venture", "pitch"]
  },
  {
    slug: "paluan-fitness",
    title: "Paluan Fitness",
    category: "SMM Design",
    image: "images/p10.jpg",
    year: "2026",
    role: "SMM designer",
    intro: "Энергичная спортивная серия для фитнес-коммуникации.",
    brief: "Показать силу, движение и понятные офферы для аудитории клуба.",
    idea: "Темные фоны, мощные заголовки и резкие акценты в стиле тренировки.",
    result: "Собраны посты, stories и промо-баннеры для регулярного контента.",
    tags: ["fitness", "sport", "SMM"]
  },
  {
    slug: "dem-group",
    title: "Dem Group",
    category: "Графический дизайн",
    image: "images/p11.jpg",
    year: "2026",
    role: "graphic designer",
    intro: "Корпоративная графика для деловой коммуникации.",
    brief: "Упаковать информацию так, чтобы она выглядела собранно и профессионально.",
    idea: "Строгая сетка, графические маркеры и визуальная иерархия без лишнего шума.",
    result: "Подготовлены макеты для презентаций, постов и деловых материалов.",
    tags: ["corporate", "layout", "presentation"]
  },
  {
    slug: "astana-venture-club",
    title: "Astana Venture Club",
    category: "SMM Design",
    image: "images/p12.jpg",
    year: "2026",
    role: "SMM designer",
    intro: "Коммуникация для предпринимательского клуба и его событий.",
    brief: "Сделать анонсы и итоги встреч узнаваемыми, плотными и удобными для чтения.",
    idea: "Редакционный подход: сильный заголовок, дата, спикер и контрастная карточка.",
    result: "Система визуалов для мероприятий, цитат и community-контента.",
    tags: ["events", "community", "venture"]
  },
  {
    slug: "kazakhstan-para-taekwondo",
    title: "Kazakhstan Para Taekwondo",
    category: "Графический дизайн",
    image: "images/p13.jpg",
    year: "2026",
    role: "graphic designer",
    intro: "Спортивная графика с уважением к атлетам и национальной команде.",
    brief: "Сделать материалы сильными, торжественными и понятными для новостей и афиш.",
    idea: "Крупная типографика, контраст, динамика движения и акценты командных цветов.",
    result: "Подготовлены визуалы для анонсов, результатов и имиджевых публикаций.",
    tags: ["sport", "team", "graphic"]
  }
];
